spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/registry
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath*:database/schema.sql
      data-locations: classpath*:database/data.sql

springdoc:
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include: health, openapi, swagger-ui, databases
  server:
    port: 9090

