spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/registry
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: false
      data-locations: classpath*:database/data.sql

springdoc:
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include: health, openapi, swagger-ui, databases
  server:
    port: 9090

